### ISSUE TITLE
Live: ImageExtractor broken ?

### ISSUE THREAD

**Issue by alexandrutodor** [dbpedia/extraction-framework#179]
Hi,

I'm getting errors while running the ImageExtractor in Live mode on the latest code base. Does anyone have an idea what could be causing this ? It's working fine in the Dump Extractoion.

2014-02-21 20:31:57,829 [PageProcessor_N2] DEBUG org.dbpedia.extraction.live.helper.LiveConfigReader: Extractors language is: wiki=de,locale=de and extractor status is: ACTIVE
2014-02-21 20:31:57,829 [PageProcessor_N1] ERROR org.dbpedia.extraction.live.processor.PageProcessor: Error in processing page number 439207, and the reason is null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.dbpedia.extraction.live.extractor.LiveExtractor$$anonfun$load$1.apply(LiveExtractor.scala:41)
	at org.dbpedia.extraction.live.extractor.LiveExtractor$$anonfun$load$1.apply(LiveExtractor.scala:39)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.dbpedia.extraction.live.extractor.LiveExtractor$.load(LiveExtractor.scala:39)
	at org.dbpedia.extraction.live.extraction.LiveExtractionConfigLoader$.LoadOntologyAndMappings(LiveExtractionConfigLoader.scala:197)
	at org.dbpedia.extraction.live.extraction.LiveExtractionConfigLoader$.startExtraction(LiveExtractionConfigLoader.scala:115)
	at org.dbpedia.extraction.live.extraction.LiveExtractionConfigLoader$.extractPage(LiveExtractionConfigLoader.scala:98)
	at org.dbpedia.extraction.live.extraction.LiveExtractionConfigLoader.extractPage(LiveExtractionConfigLoader.scala)
	at org.dbpedia.extraction.live.processor.PageProcessor.processPage(PageProcessor.java:46)
	at org.dbpedia.extraction.live.processor.PageProcessor.run(PageProcessor.java:74)
Caused by: java.lang.NullPointerException
	at org.dbpedia.extraction.mappings.ImageExtractor$.org$dbpedia$extraction$mappings$ImageExtractor$$loadImages(ImageExtractor.scala:218)
	at org.dbpedia.extraction.mappings.ImageExtractor.<init>(ImageExtractor.scala:52)
	... 18 more

**Comment by jimkont** [comment]
for now, images are loaded on the static graph and are not extracted live
