### ISSUE TITLE
New Dynamic Extractors from Wikipedia Content with JSONpedia Faceted Browsing

### ISSUE THREAD

**Issue by michelemostarda** [dbpedia/extraction-framework#356]
* Clone the latest JSONpedia snapshot release from here: https://bitbucket.org/hardest/jsonpedia
and read the documentation.
* Install Elasticsearch 1.0.1 (subsequent versions have not yet been tested but you're welcome to do it).
* Optionally install MongoDB 2.4.9 (subsequent versions have not yet been tested but you're welcome do to it).
* Configure JSONpedia (conf/default/properties) to work properly with your installations of Elasticsearch and optionally MongoDB.
* Process with JSONpedia the first 3 Wikipedia dumps [1] into Elasticsearch and optionally MongoDB (both manually or using the script bin/loader.py)
* Load the faceted indexes using script bin/facet_loader.py
* Run a local JSONpedia service [2] and verify the faceted browser in properly working.

[1] http://dumps.wikimedia.org/enwiki/latest/
[2] http://localhost:PORT/frontend/facet.html?source={"query":{"match_all":{}},"size":20}

**Comment by navinpai** [comment]
Hey, the link [1] mentioned lists a whole set of dumps... I'm not sure what you meant by "the first 3 wikipedia dumps"

What I see is:

```
../
enwiki-latest-abstract.xml                         05-Mar-2015 06:42          4505182240
enwiki-latest-abstract.xml-rss.xml                 05-Mar-2015 06:42                 751
enwiki-latest-abstract1.xml                        05-Mar-2015 05:29           745284563
enwiki-latest-abstract1.xml-rss.xml                05-Mar-2015 06:39                 754
enwiki-latest-abstract10.xml                       05-Mar-2015 04:34           160439500
enwiki-latest-abstract10.xml-rss.xml               05-Mar-2015 06:40                 757
.
.
.
.
enwiki-latest-templatelinks.sql.gz-rss.xml         04-Mar-2015 23:15                 775
enwiki-latest-user_groups.sql.gz                   04-Mar-2015 23:27               75327
enwiki-latest-user_groups.sql.gz-rss.xml           04-Mar-2015 23:27                 769
```
Which of these should I be processing?

My setup right now is: elasticsearch v1.0.1, mongodb v2.4.11 with the latest JSONpedia snapshot

Thanks
Navin

**Comment by navinpai** [comment]
Hey,
On running facet_loader.py I get the error log shown below.

```
Executing command: gradle runFacetLoader -Pargs_line='-s localhost:9200:jsonpedia:en -d localhost:9200:jsonpedia_facet:en -l 1 -c conf/faceting.properties'
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:runFacetLoader
19:56:52,351  INFO plugins:114 - [Seth] loaded [], sites []
19:56:58,004  INFO transport:119 - [Seth] failed to get node info for [#transport#-1][igritte][inet[localhost/127.0.0.1:9200]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[localhost/127.0.0.1:9200]][cluster/nodes/info] request_id [0] timed out after [5003ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:356)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Error while loading faceting index.
org.elasticsearch.client.transport.NoNodeAvailableException: No node available
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:219)
	at org.elasticsearch.client.transport.support.InternalTransportIndicesAdminClient.execute(InternalTransportIndicesAdminClient.java:85)
	at org.elasticsearch.client.support.AbstractIndicesAdminClient.delete(AbstractIndicesAdminClient.java:265)
	at org.elasticsearch.action.admin.indices.delete.DeleteIndexRequestBuilder.doExecute(DeleteIndexRequestBuilder.java:68)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
	at com.machinelinking.storage.elasticsearch.ElasticJSONStorageConnection.dropCollection(ElasticJSONStorageConnection.java:145)
	at com.machinelinking.storage.elasticsearch.ElasticJSONStorage.deleteCollection(ElasticJSONStorage.java:99)
	at com.machinelinking.storage.elasticsearch.ElasticJSONStorage.deleteCollection(ElasticJSONStorage.java:91)
	at com.machinelinking.cli.facetloader.run(facetloader.java:79)
	at com.machinelinking.cli.facetloader.main(facetloader.java:68)
:runFacetLoader FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runFacetLoader'.
> Process 'command '/usr/lib/jvm/jdk1.7.0/bin/java'' finished with non-zero exit value 3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.489 secs
Traceback (most recent call last):
  File "./bin/facet_loader.py", line 31, in <module>
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gradle runFacetLoader -Pargs_line='-s localhost:9200:jsonpedia:en -d localhost:9200:jsonpedia_facet:en -l 1 -c conf/faceting.properties'' returned non-zero exit status 1
```

Any idea why this is happening?

**Comment by ANKIT-KS** [comment]
Getting this error while executing: gradle build
-------------------------------------------------
:compileJava
/home/ankit/jsonpedia/src/main/java/com/machinelinking/storage/elasticsearch/faceting/EnrichedEntityFacetConverter.java:81: error: incomparable types: int and Object
            if (sectionIndex == linkMap.get("section_idx")) {
                             ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileJava FAILED
-------------------------------------------------
any suggesttions as to how to get over this error??

**Comment by michelemostarda** [comment]
Sorry reading now.
enwiki-latest-pages-articles1.xml-p000000010p000010000.bz2 
enwiki-latest-pages-articles2.xml-p000010002p000024999.bz2 
enwiki-latest-pages-articles3.xml-p000025001p000055000.bz2
As extracted by the bin/loader.py script, but I guess you already understood!

**Comment by michelemostarda** [comment]
Going to close this issue and move it in the specific JSONpedia subproject [1] issue tracker.
Please refer to [1] to followups.

[1] https://github.com/dbpedia/jsonpedia-extractor/issues/14
