### ISSUE TITLE
Issues when downloading with wiktrionary

### ISSUE THREAD

**Issue by tgalery** [dbpedia/extraction-framework#418]
Hi there, I've pulled the latest build and did a `mvn clean install`. I then provided a minimal config for the download task along these lines:

```
# NOTE: format is not java.util.Properties, but org.dbpedia.extraction.dump.download.DownloadConfig
# Default download server. It lists mirrors which may be faster. 
base-url=http://dumps.wikimedia.org/
# Replace by your target folder.
base-dir=/home/intruder/datasets/dbpedia
# Replace xx by your language.
download=pt:pages-articles.xml.bz2
# Unzip files while downloading? Not necessary, extraction will unzip on the fly. Let's save space.
unzip=false

# Sometimes connecting to the server fails, so we try five times with pauses of 10 seconds.
retry-max=5
retry-millis=10000
```

When I execute `./run download config=../download.properties` the task downloads the portuguese dump as specified in the config, but it throws the following error when trying to execute the wiktionary download task

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.lang.Exception: Invalid file /home/intruder/source/ca/wikimedia-extractor/dbpedia-extractor/extraction-framework/download.properties in 'config=download.properties'
	at org.dbpedia.extraction.dump.download.Usage$.apply(DownloadConfig.scala:190)
	at org.dbpedia.extraction.dump.download.DownloadConfig$$anonfun$parse$2.apply(DownloadConfig.scala:73)
	at org.dbpedia.extraction.dump.download.DownloadConfig$$anonfun$parse$2.apply(DownloadConfig.scala:59)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at org.dbpedia.extraction.dump.download.DownloadConfig.parse(DownloadConfig.scala:59)
	at org.dbpedia.extraction.dump.download.Download$.main(Download.scala:23)
	at org.dbpedia.extraction.dump.download.Download.main(Download.scala)
	... 6 more
```

Is there something I'm doing wrong ?

**Comment by jimkont** [comment]
it complains that `/home/intruder/source/ca/wikimedia-extractor/dbpedia-extractor/extraction-framework/download.properties` does not exists.
Can you double check the file or the file permissions in order to investigate further?

**Comment by tgalery** [comment]
My bad dimitris, I had the file one level below it. It seems that relative paths via the cli are not parsed that well ? I just move it and it works like a charm. Closing this issue now
