### ISSUE TITLE
Wikidata parsing issue

### ISSUE THREAD

**Issue by tgalery** [dbpedia/extraction-framework#419]
Hi guys, I'm trying to run the dbpedia extraction on the wikidata wiki and after 2 days I got the following error:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.lang.NoClassDefFoundError: org/dbpedia/extraction/util/Workers$$anonfun$stop$1
	at org.dbpedia.extraction.util.Workers.stop(Workers.scala:173)
	at org.dbpedia.extraction.dump.extract.ExtractionJob.run(ExtractionJob.scala:51)
	at org.dbpedia.extraction.dump.extract.Extraction$$anonfun$main$2.apply(Extraction.scala:30)
	at org.dbpedia.extraction.dump.extract.Extraction$$anonfun$main$2.apply(Extraction.scala:30)
	at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.immutable.RedBlackTree$TreeIterator.foreach(RedBlackTree.scala:468)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.IterableLike$$anon$1.foreach(IterableLike.scala:310)
	at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168)
	at scala.collection.IterableViewLike$$anon$3.foreach(IterableViewLike.scala:113)
	at org.dbpedia.extraction.dump.extract.Extraction$.main(Extraction.scala:30)
	at org.dbpedia.extraction.dump.extract.Extraction.main(Extraction.scala)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.dbpedia.extraction.util.Workers$$anonfun$stop$1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

```
Here is the config file used:

```
# download and extraction target dir
base-dir=/home/intruder/datasets/dbpedia


# Source file. If source file name ends with .gz or .bz2, it is unzipped on the fly. 
# Must exist in the directory xxwiki/yyyymmdd and have the prefix xxwiki-yyyymmdd-
# where xx is the wiki code and yyyymmdd is the dump date.
 
# default:
source=pages-articles.xml.bz2

# alternatives:
# source=pages-articles.xml.gz
# source=pages-articles.xml

###### Extract from part files ######
#
# Please make sure that the regex actually matches the format used by ALL the wikis you are going to extract from!!!!
# One that should work in all cases is
# source=@pages-articles\\d*\\.xml(-p\\d+p\\d+)?\\.bz2
#
# NOTE: when using the above regex you should make sure you do not have part files AND regular dump files together
# for the same wiki, e.g. frwiki-20131120-pages-articles1.xml.bz2 and frwiki-20131120-pages-articles.xml.bz2, as they
# BOTH will match and that will result in duplicate output data
#
# Example:
# enwiki => enwiki-latest-pages-articles1.xml-p000000010p000010000.bz2 hence @pages-articles\\d+\\.xml-p\\d+p\\d+\\.bz2 matches
# frwiki => frwiki-latest-pages-articles1.xml.bz2 hence @pages-articles\\d+\\.xml\\.bz2 matches (the previous regex does not!)
# commonswiki => it does not have part files! This is true for other wikis as well.
#
# source=@pages-articles\\d+\\.xml-p\\d+p\\d+\\.bz2

# In case of multistream chunks
# source=@pages-articles-multistream\\.xml\\.\\d+\\.bz2

# use only directories that contain a 'download-complete' file? Default is .
require-download-complete=true

# List of languages or article count ranges, e.g. 'en,de,fr' or '10000-20000' or '10000-', or '@mappings'
languages=wikidata	

extractors.wikidata=.WikidataSameAsExtractor, .WikidataNameSpaceSameAsExtractor,.WikidataPropertyExtractor

# if ontology and mapping files are not given or do not exist, download info from mappings.dbpedia.org
ontology=../ontology.xml
mappings=../mappings

# Serialization URI policies and file formats. Quick guide:
# uri-policy keys: uri, generic, xml-safe, reject-long
# uri-policy position modifiers: -subjects, -predicates, -objects, -datatypes, -contexts
# uri-policy values: comma-separated languages or '*' for all languages
# format values: n-triples, n-quads, turtle-triples, turtle-quads, trix-triples, trix-quads
# See http://git.io/DBpedia-serialization-format-properties for details.

# For backwards compatibility, en uses generic URIs. All others use local IRIs.
# uri-policy.uri=uri:en; generic:en; xml-safe-predicates:*; reject-long:*
uri-policy.iri=generic:en; xml-safe-predicates:*; reject-long:*

# NT is unreadable anyway - might as well use URIs for en
#format.nt.gz=n-triples;uri-policy.uri
#format.nq.gz=n-quads;uri-policy.uri

# Turtle is much more readable - use nice IRIs for all languages
format.ttl.bz2=turtle-triples;uri-policy.iri
format.tql.bz2=turtle-quads;uri-policy.iri
```

Anything I'm doing obviously wrong ?

**Comment by jimkont** [comment]
#127 seems related, can you do a clean install / delete .m2 folder and try again?

**Comment by jimkont** [comment]
@tgalery is this fixed btw?

**Comment by tgalery** [comment]
Hi dimitris, I wll try to run again this weekend and update the issue.

**Comment by chile12** [comment]
issue seems to be resolved
