### ISSUE TITLE
Ontology Properties not found && NoSuchMethodError

### ISSUE THREAD

**Issue by julyana** [dbpedia/extraction-framework#449]
During the process of executing extraction application, I got following warnings and error.

- First,it can not find enwiki-20160407-disambiguations-ids.obj;

- Then, it couldn't load properties, one of the warnings is as follow: Couldn't load property mapping on page Mapping en:Infobox Automobile engine generation. Details: Ontology property not found: valvetrain (java.lang.IllegalArgumentException: Ontology property not found: valvetrain)

- Then,it gave the warnings like this: PM org.dbpedia.extraction.sources.WikipediaDumpParser readPageWARNING: Error parsing title: found namespace 3/User talk, expected 0/Main in title User talk:Dralwik

- Last,it stopped at this:Caused by: java.lang._NoSuchMethodError_: org.dbpedia.extraction.destinations.DBpediaDatasets$._FlickrWrapprLinks_()Lorg/dbpedia/extraction/destinations/Dataset;

Can someone gives some suggestions on how to solve the warnings and Error?

**Comment by jimkont** [comment]
the framework displays some warnings / non fatal errors as it extracts data but as long as it does not fail completely it is working.

in your case all except `Caused by: java.lang.NoSuchMethodError: org.dbpedia.extraction.destinations.DBpediaDatasets$.FlickrWrapprLinks()Lorg/dbpedia/extraction/destinations/Dataset` were ok, can you give some more context arounnd the last error?

also make sure you run the latest code from github

**Comment by julyana** [comment]
After I repull the code, the warnings I mentioned disappear. and the error is as follow:

Exception in thread "main" java.lang.ClassNotFoundException: org.dbpedia.extraction.mappings.FlickrWrapprLinkExtractor
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.dbpedia.extraction.util.ExtractorUtils$.loadExtractorClass(ExtractorUtils.scala:32)
	at org.dbpedia.extraction.util.ExtractorUtils$$anonfun$1$$anonfun$apply$1.apply(ExtractorUtils.scala:62)
	at org.dbpedia.extraction.util.ExtractorUtils$$anonfun$1$$anonfun$apply$1.apply(ExtractorUtils.scala:62)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.dbpedia.extraction.util.ExtractorUtils$$anonfun$1.apply(ExtractorUtils.scala:62)
	at org.dbpedia.extraction.util.ExtractorUtils$$anonfun$1.apply(ExtractorUtils.scala:58)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.dbpedia.extraction.util.ExtractorUtils$.loadExtractorsMapFromConfig(ExtractorUtils.scala:58)
	at org.dbpedia.extraction.dump.extract.Config.loadExtractorClasses(Config.scala:79)
	at org.dbpedia.extraction.dump.extract.Config.<init>(Config.scala:58)
	at org.dbpedia.extraction.dump.extract.Extraction$.main(Extraction.scala:27)
	at org.dbpedia.extraction.dump.extract.Extraction.main(Extraction.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by jimkont** [comment]
`FlickrWrapprLinkExtractor` was recently deleted as obsolete but some references remained in the comnfigurations, the last commit fixed that.

make sure you remove the `FlickrWrapprLinkExtractor` from any local extraction configuration

**Comment by julyana** [comment]
After pulling the newest code, it has been extracting pages for hours without an error. Thank you for solving the problem!
