### ISSUE TITLE
Issue when downloading dump

### ISSUE THREAD

**Issue by ramkarnani** [dbpedia/extraction-framework#460]
Hi
I have pulled the latest build and did **mvn clean install** and provided the configuration for downloading (in the file **download.properties** in directory **/home/ramkarnani/extraction-framework/dump** with permissions set  **777** ) as following:
`base-url=https://dumps.wikimedia.org/
base-dir=/home/ramkarnani/datasets/dbpedia
download=en:pages-articles.xml.bz2
unzip=false
retry-max=5
retry-millis=10000
`
and executed the following command
`../run download config=./download.properties`

but getting the error:

> [INFO] launcher 'download' selected => org.dbpedia.extraction.dump.download.Download
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.lang.ExceptionInInitializerError
	at org.dbpedia.extraction.dump.download.DownloadConfig$$anonfun$parse$2$$anonfun$apply$2.apply(DownloadConfig.scala:82)
	at org.dbpedia.extraction.dump.download.DownloadConfig$$anonfun$parse$2$$anonfun$apply$2.apply(DownloadConfig.scala:77)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.dbpedia.extraction.dump.download.DownloadConfig$$anonfun$parse$2.apply(DownloadConfig.scala:77)
	at org.dbpedia.extraction.dump.download.DownloadConfig$$anonfun$parse$2.apply(DownloadConfig.scala:59)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at org.dbpedia.extraction.dump.download.DownloadConfig.parse(DownloadConfig.scala:59)
	at org.dbpedia.extraction.dump.download.DownloadConfig.parse(DownloadConfig.scala:45)
	at org.dbpedia.extraction.dump.download.DownloadConfig$$anonfun$parse$2.apply(DownloadConfig.scala:74)
	at org.dbpedia.extraction.dump.download.DownloadConfig$$anonfun$parse$2.apply(DownloadConfig.scala:59)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at org.dbpedia.extraction.dump.download.DownloadConfig.parse(DownloadConfig.scala:59)
	at org.dbpedia.extraction.dump.download.Download$.main(Download.scala:23)
	at org.dbpedia.extraction.dump.download.Download.main(Download.scala)
	... 6 more
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at scala.io.Source$.fromURL(Source.scala:141)
	at scala.io.Source$.fromURL(Source.scala:131)
	at org.dbpedia.extraction.util.Language$.<init>(Language.scala:89)
	at org.dbpedia.extraction.util.Language$.<clinit>(Language.scala)
	... 23 more
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
	at sun.security.validator.Validator.getInstance(Validator.java:179)
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	... 34 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
	... 46 more

Anything i am doing wrong ?

**Comment by jimkont** [comment]
This looks like an https / ssl error for the `base-url=https://dumps.wikimedia.org/`.
```
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```
Are you behind a proxy or have any strange network settings?
Otherwise it might was a temporary problem and goes away if you try again

**Comment by ramkarnani** [comment]
Hi
The problem was coming due to openjdk-8 installation. When we install openjdk-8, the link from 
> /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts **to**  /etc/ssl/certs/java/cacerts 
is broken, so we need to fix this link.
Executed the following instruction and it worked fine then
`update-ca-certificates -f`

Reference--> [http://stackoverflow.com/questions/4764611/java-security-invalidalgorithmparameterexception-the-trustanchors-parameter-mus](url)

Closing the issue now.
Thank You
