### ISSUE TITLE
[Error] ../run download config=download-config-file

### ISSUE THREAD

**Issue by mayank-chutani** [dbpedia/extraction-framework#478]
`java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.lang.Exception: Invalid file /home/mchutani/work/github/extraction-framework/dump/download-config-file in 'config=download-config-file'
	at org.dbpedia.extraction.dump.download.Usage$.apply(DownloadConfig.scala:191)
	at org.dbpedia.extraction.dump.download.DownloadConfig$$anonfun$parse$2.apply(DownloadConfig.scala:73)
	at org.dbpedia.extraction.dump.download.DownloadConfig$$anonfun$parse$2.apply(DownloadConfig.scala:59)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at org.dbpedia.extraction.dump.download.DownloadConfig.parse(DownloadConfig.scala:59)
	at org.dbpedia.extraction.dump.download.Download$.main(Download.scala:23)
	at org.dbpedia.extraction.dump.download.Download.main(Download.scala)
	... 6 more`

`[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.157 s
[INFO] Finished at: 2016-08-28T14:26:39+05:30
[INFO] Final Memory: 19M/332M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:run (default-cli) on project dump: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by mayank-chutani** [comment]
@jimkont Could you please help here or tag someone who can help?

**Comment by jimkont** [comment]
`Caused by: java.lang.Exception: Invalid file
/home/mchutani/work/github/extraction-framework/dump/download-config-file
in 'config=download-config-file'`

From the log it looks like the config file does not exists

Typed by thumb. Please forgive brevity, errors.

**Comment by mayank-chutani** [comment]
@jimkont So can you add a config file or tell me how can I create one?

**Comment by jimkont** [comment]
have a look [here](https://github.com/dbpedia/extraction-framework/tree/master/dump)  and let me know if you need more help

**Comment by jimkont** [comment]
if the documentation is confusing, could you please adjust it to make it easier to understand?
