### ISSUE TITLE
Network proxy issue when running the "./run download" 

### ISSUE THREAD

**Issue by kpadmanabhan-ryerson** [dbpedia/extraction-framework#481]
I have used extraction frame successfully before. However when I tried to run it recently I got the following error. I am able to successfully access the link from browser.

Java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
    at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.lang.Exception: found no date - http://dumps.wikimedia.org/enwiki/ is probably broken or unreachable. check your network / proxy settings.
    at org.dbpedia.extraction.dump.download.LanguageDownloader.downloadDates(LanguageDownloader.scala:40)
    at org.dbpedia.extraction.dump.download.Download$$anonfun$main$3.apply(D

**Comment by jimkont** [comment]
if it has been a while since you last run it might me the http/https change of all the wikimedia domains.
try changing `http://dumps.wikimedia.org` in edited your download config (or use one of the default)

**Comment by m1ci** [comment]
@kpadmanabhan-ryerson all good here? Can we close the issue?
