### ISSUE TITLE
Get http 502 Bad Gateway response when downloading wikipedias.csv

### ISSUE THREAD

**Issue by wakakalu** [dbpedia/extraction-framework#546]
After running the command `../run download download.minimal.properties`, I got an error caused by http 502 response when the program is trying to download wikipedias.csv.
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.dbpedia.extraction:dump:jar:4.2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.sonatype.plugins:nexus-staging-maven-plugin is missing. @ org.dbpedia:extraction:4.2-SNAPSHOT, /home/apa/code/openSource/extraction-framework/pom.xml, line 143, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ org.dbpedia:extraction:4.2-SNAPSHOT, /home/apa/code/openSource/extraction-framework/pom.xml, line 154, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building DBpedia Dump Extraction 4.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> scala-maven-plugin:3.2.0:run (default-cli) @ dump >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (default) @ dump ---
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:add-source (attach-docs-sources) @ dump ---
[INFO] Add Source directory: /home/apa/code/openSource/extraction-framework/dump/src/main/scala
[INFO] Add Test Source directory: /home/apa/code/openSource/extraction-framework/dump/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (doc) @ dump ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ dump ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/apa/code/openSource/extraction-framework/dump/src/main/resources
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (process-resources) @ dump ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ dump ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (compile) @ dump ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ dump ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/apa/code/openSource/extraction-framework/dump/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ dump ---
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:testCompile (test-compile) @ dump ---
[INFO] No sources to compile
[INFO] 
[INFO] <<< scala-maven-plugin:3.2.0:run (default-cli) @ dump <<<
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:run (default-cli) @ dump ---
[INFO] launcher 'download' selected => org.dbpedia.extraction.dump.download.Download
Apr 15, 2018 2:51:47 PM org.dbpedia.extraction.util.Language$$anonfun$4 apply
WARNING: Language not found: be-x-old. To extract this language, please edit the addonLanguage.json in core.
Apr 15, 2018 2:51:47 PM org.dbpedia.extraction.util.Language$$anonfun$4 apply
WARNING: Language not found: cbk-zam. To extract this language, please edit the addonLanguage.json in core.
Apr 15, 2018 2:51:47 PM org.dbpedia.extraction.util.Language$$anonfun$4 apply
WARNING: Language not found: fiu-vro. To extract this language, please edit the addonLanguage.json in core.
Apr 15, 2018 2:51:47 PM org.dbpedia.extraction.util.Language$$anonfun$4 apply
WARNING: Language not found: map-bms. To extract this language, please edit the addonLanguage.json in core.
Apr 15, 2018 2:51:47 PM org.dbpedia.extraction.util.Language$$anonfun$4 apply
WARNING: Language not found: nds-nl. To extract this language, please edit the addonLanguage.json in core.
Apr 15, 2018 2:51:47 PM org.dbpedia.extraction.util.Language$$anonfun$4 apply
WARNING: Language not found: roa-rup. To extract this language, please edit the addonLanguage.json in core.
Apr 15, 2018 2:51:47 PM org.dbpedia.extraction.util.Language$$anonfun$4 apply
WARNING: Language not found: roa-tara. To extract this language, please edit the addonLanguage.json in core.
Apr 15, 2018 2:51:47 PM org.dbpedia.extraction.util.Language$$anonfun$4 apply
WARNING: Language not found: zh-classical. To extract this language, please edit the addonLanguage.json in core.
downloading 'http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv' to '/data/extraction-data/2017-08/wikipedias.csv'
1 of 5 attempts to download 'http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv' to '/data/extraction-data/2017-08/wikipedias.csv' failed - java.io.IOException: Server returned HTTP response code: 502 for URL: http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv
downloading 'http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv' to '/data/extraction-data/2017-08/wikipedias.csv'
2 of 5 attempts to download 'http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv' to '/data/extraction-data/2017-08/wikipedias.csv' failed - java.io.IOException: Server returned HTTP response code: 502 for URL: http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv
downloading 'http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv' to '/data/extraction-data/2017-08/wikipedias.csv'
3 of 5 attempts to download 'http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv' to '/data/extraction-data/2017-08/wikipedias.csv' failed - java.io.IOException: Server returned HTTP response code: 502 for URL: http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv
downloading 'http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv' to '/data/extraction-data/2017-08/wikipedias.csv'
4 of 5 attempts to download 'http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv' to '/data/extraction-data/2017-08/wikipedias.csv' failed - java.io.IOException: Server returned HTTP response code: 502 for URL: http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv
downloading 'http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv' to '/data/extraction-data/2017-08/wikipedias.csv'
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
5 of 5 attempts to download 'http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv' to '/data/extraction-data/2017-08/wikipedias.csv' failed - java.io.IOException: Server returned HTTP response code: 502 for URL: http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at org.dbpedia.extraction.dump.download.FileDownloader$class.inputStream(FileDownloader.scala:65)
	at org.dbpedia.extraction.dump.download.Download$Downloader$1.org$dbpedia$extraction$dump$download$Counter$$super$inputStream(Download.scala:22)
	at org.dbpedia.extraction.dump.download.Counter$class.inputStream(Counter.scala:23)
	at org.dbpedia.extraction.dump.download.Download$Downloader$1.inputStream(Download.scala:22)
	at org.dbpedia.extraction.dump.download.FileDownloader$class.downloadFile(FileDownloader.scala:49)
	at org.dbpedia.extraction.dump.download.Download$Downloader$1.org$dbpedia$extraction$dump$download$LastModified$$super$downloadFile(Download.scala:22)
	at org.dbpedia.extraction.dump.download.LastModified$class.downloadFile(LastModified.scala:21)
	at org.dbpedia.extraction.dump.download.Download$Downloader$1.downloadFile(Download.scala:22)
	at org.dbpedia.extraction.dump.download.FileDownloader$class.downloadFile(FileDownloader.scala:36)
	at org.dbpedia.extraction.dump.download.Download$Downloader$1.org$dbpedia$extraction$dump$download$Retry$$super$downloadFile(Download.scala:22)
	at org.dbpedia.extraction.dump.download.Retry$class.downloadFile(Retry.scala:28)
	at org.dbpedia.extraction.dump.download.Download$Downloader$1.downloadFile(Download.scala:22)
	at org.dbpedia.extraction.dump.download.Download$.main(Download.scala:35)
	at org.dbpedia.extraction.dump.download.Download.main(Download.scala)
	... 6 more
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: http://wikistats.wmflabs.org/api.php?action=dump&table=wikipedias&format=csv
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3000)
	at java.net.HttpURLConnection.getHeaderFieldDate(HttpURLConnection.java:552)
	at java.net.URLConnection.getLastModified(URLConnection.java:559)
	at org.dbpedia.extraction.dump.download.LastModified$class.downloadFile(LastModified.scala:17)
	... 13 more
```
Could anyone here please help me figure it out?

Sikei Ko,
Thanks

**Comment by alismayilov** [comment]
The reason for this error was http://wikistats.wmflabs.org/ was download completely for several days. It is up and running again. You should be able to run the command again.

**Comment by wakakalu** [comment]
Indeed, thanks a lot. @alismayilov
