### ISSUE TITLE
Problem with importing dump

### ISSUE THREAD

**Issue by VladislavOshkanov** [dbpedia/extraction-framework#547]
Hello.

When I execute `../run import`, the following error happens:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.lang.AssertionError: assertion failed: Importer needs a single parameter: the path to the pertaining properties file (see: mysql.import.properties).
	at scala.Predef$.assert(Predef.scala:165)
	at org.dbpedia.extraction.dump.sql.Import$.main(Import.scala:22)
	at org.dbpedia.extraction.dump.sql.Import.main(Import.scala)
	... 6 more
```

I have already changed path to dump, to tables.sql file and set password to my database in mysql.import.properties file, but error still happens. 

Please, let me know possible solution

**Comment by interviewBubble** [comment]
It will be like this
`../run import mysql.import.properties`

**Comment by VladislavOshkanov** [comment]
Thanks a lot, @interviewBubble
