### ISSUE TITLE
TooManyErrorsException

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/extraction-framework#548]
http://mappings.dbpedia.org/server/extraction/en/extract?title=&revid=723237297&format=turtle-triples&extractors=mappings

`Stacktrace:	org.dbpedia.extraction.wikiparser.impl.simple.TooManyErrorsException: Too many errors at ' |label1=' (line: 100) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseUntil(SimpleWikiParser.scala:120) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseProperty(SimpleWikiParser.scala:544) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseTemplate(SimpleWikiParser.scala:521) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.createNodes(SimpleWikiParser.scala:273) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseUntil(SimpleWikiParser.scala:203) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseProperty(SimpleWikiParser.scala:556) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseTemplate(SimpleWikiParser.scala:521) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.createNodes(SimpleWikiParser.scala:273) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseUntil(SimpleWikiParser.scala:203) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseProperty(SimpleWikiParser.scala:556) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseTemplate(SimpleWikiParser.scala:521) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.createNodes(SimpleWikiParser.scala:273) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseUntil(SimpleWikiParser.scala:203) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseProperty(SimpleWikiParser.scala:556) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseTemplate(SimpleWikiParser.scala:521) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.createNodes(SimpleWikiParser.scala:273) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseUntil(SimpleWikiParser.scala:203) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseProperty(SimpleWikiParser.scala:556) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseTemplate(SimpleWikiParser.scala:521) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.createNodes(SimpleWikiParser.scala:273) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.parseUntil(SimpleWikiParser.scala:203) at org.dbpedia.extraction.wikiparser.impl.simple.SimpleWikiParser.apply(SimpleWikiParser.scala:75) at org.dbpedia.extraction.mappings.WikiParseExtractor.extract(WikiParseExtractor.scala:29) at org.dbpedia.extraction.mappings.WikiParseExtractor.extract(WikiParseExtractor.scala:22) at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14) at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252) at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104) at org.dbpedia.extraction.mappings.CompositeExtractor.extract(CompositeExtractor.scala:14) at org.dbpedia.extraction.mappings.CompositeParseExtractor.extract(CompositeParseExtractor.scala:54) at org.dbpedia.extraction.mappings.CompositeParseExtractor.extract(CompositeParseExtractor.scala:11) at org.dbpedia.extraction.mappings.RootExtractor.apply(RootExtractor.scala:24) at org.dbpedia.extraction.server.ExtractionManager$$anonfun$extract$1.apply(ExtractionManager.scala:64) at org.dbpedia.extraction.server.ExtractionManager$$anonfun$extract$1.apply(ExtractionManager.scala:64) at org.dbpedia.extraction.util.WikiApi$$anonfun$processPages$1$$anonfun$apply$1.apply(WikiApi.scala:139) at org.dbpedia.extraction.util.WikiApi$$anonfun$processPages$1$$anonfun$apply$1.apply(WikiApi.scala:131) at scala.collection.Iterator$class.foreach(Iterator.scala:743) at scala.collection.AbstractIterator.foreach(Iterator.scala:1195) at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) at scala.collection.AbstractIterable.foreach(Iterable.scala:54) at org.dbpedia.extraction.util.WikiApi$$anonfun$processPages$1.apply(WikiApi.scala:131) at org.dbpedia.extraction.util.WikiApi$$anonfun$processPages$1.apply(WikiApi.scala:130) at scala.collection.Iterator$class.foreach(Iterator.scala:743) at scala.collection.AbstractIterator.foreach(Iterator.scala:1195) at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) at scala.collection.AbstractIterable.foreach(Iterable.scala:54) at org.dbpedia.extraction.util.WikiApi.processPages(WikiApi.scala:130) at org.dbpedia.extraction.util.WikiApi$$anon$1$$anonfun$foreach$1.apply(WikiApi.scala:106) at org.dbpedia.extraction.util.WikiApi$$anon$1$$anonfun$foreach$1.apply(WikiApi.scala:103) at scala.collection.Iterator$class.foreach(Iterator.scala:743) at scala.collection.AbstractIterator.foreach(Iterator.scala:1195) at org.dbpedia.extraction.util.WikiApi$$anon$1.foreach(WikiApi.scala:103) at org.dbpedia.extraction.sources.WikiSource$$anon$1.foreach(WikiSource.scala:56) at org.dbpedia.extraction.server.ExtractionManager.extract(ExtractionManager.scala:64) at org.dbpedia.extraction.server.resources.Extraction.extract(Extraction.scala:131) at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:601) at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288) at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1483) at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1414) at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1363) at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1353) at com.sun.jersey.server.impl.container.httpserver.HttpHandlerContainer.handle(HttpHandlerContainer.java:191) at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77) at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83) at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80) at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:668) at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77) at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:640) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:722)`

**Comment by mgns** [comment]
The wiki syntax is corrupt, see https://en.wikipedia.org/w/index.php?oldid=723237297#Acquisition_history

Questionable, whether this is a bug or intended behavior.
