### ISSUE TITLE
NullPointerException when trying to import dump into MySQL

### ISSUE THREAD

**Issue by m1ci** [dbpedia/extraction-framework#567]
I get following null pointer  when I try to import a wikipedia dump int mysql
```../run import mysql.import.properties```

The null pointer comes from line 309 https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/util/ExtractionRecorder.scala#L309

which is called from the initialized function
https://github.com/dbpedia/extraction-framework/blob/master/dump/src/main/scala/org/dbpedia/extraction/dump/sql/Import.scala#L76

Any ideas what is wrong here?
 
```
Exception in thread “Thread-1” java.lang.NullPointerException
    at org.dbpedia.extraction.util.ExtractionRecorder.initialize(ExtractionRecorder.scala:309)
    at org.dbpedia.extraction.dump.sql.Import$$anonfun$main$2.apply(Import.scala:76)
    at org.dbpedia.extraction.dump.sql.Import$$anonfun$main$2.apply(Import.scala:40)
    at org.dbpedia.extraction.util.SimpleWorkers$$anonfun$apply$1$$anon$2.process(Workers.scala:43)
    at org.dbpedia.extraction.util.Workers$$anonfun$1$$anon$1.run(Workers.scala:234)
```

**Comment by m1ci** [comment]
fixed by @JJ-Author, the fix is here: with https://github.com/dbpedia/extraction-framework/commit/b829d0406a9e735ac9fffbd48b673dd55ec9e57b 

good job @JJ-Author !
