### ISSUE TITLE
Can't download the config-file

### ISSUE THREAD

**Issue by HadeCamacho** [dbpedia/extraction-framework#570]
[INFO] launcher 'download' selected => org.dbpedia.extraction.dump.download.Download
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
        at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.io.FileNotFoundException: config=download-config-file (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.dbpedia.extraction.config.ConfigUtils$.loadConfig(ConfigUtils.scala:49)
        at org.dbpedia.extraction.config.Config.<init>(Config.scala:29)
        at org.dbpedia.extraction.dump.download.DownloadConfig.<init>(DownloadConfig.scala:13)
        at org.dbpedia.extraction.dump.download.Download$.main(Download.scala:16)
        at org.dbpedia.extraction.dump.download.Download.main(Download.scala)
        ... 6 more

Already done with the maven clean install problem is I cant install the wikipedia dumps. My os is windows so I use the command ( mvn scala:run "-Dlauncher=download"   "-DaddArgs=config=download-config-file" ) unfortunately it didn't work out. Do I have to do something else first or I was not able to follow the docs? https://github.com/dbpedia/extraction-framework/wiki/Extraction-Instructions

**Comment by JJ-Author** [comment]
Hi, I never ran a dump extraction but AFAIK, the config file should be a .properties file. (which yours seems not). Furthermore I would suggest to use the run script instead from within the dump folder ../run download config.properties or try ../run download config=download.properties
i assume it then looks in the dump folder for the specified config file. I hope this helps

**Comment by JJ-Author** [comment]
from your log.txt I can see that it still is called wrong:

`[DEBUG] properties used {``
...
addArgs=config=download-config-file
...
env.MAVEN_CMD_LINE_ARGS=scala:run "-Dlauncher=download"   "-DaddArgs=config=download-config-file" -X,
Dlauncher=download -DaddArgs=config=download-config-file -X,
```
you should try without config= and pass a valid and existing .properties filename ( this of course inlcudes the file name extension as well) example config files are in the dump folder). both things are not done in the call you pasted the log from. 

If you are struggling with command line on Windows you could also try to run the Downloader from within IntelliJ (see e.g. https://extremeprinciple.blogspot.com/2017/11/setting-up-intellij-to-work-with.html ) but I would actually love to hear from you how to call it properly under windows and then update the wiki page you mentioned which seems wrong / outdated.

**Comment by HadeCamacho** [comment]
oh, after running the command within the dump folder ( mvn scala:run "-Dlauncher=download" "-DaddArgs=config.properties" ) the log changed.

[INFO] launcher 'download' selected => org.dbpedia.extraction.dump.download.Download
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
        at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.lang.IllegalArgumentException: Properties file is lacking this property: base-url
        at org.dbpedia.extraction.dump.download.DownloadConfig.<init>(DownloadConfig.scala:17)
        at org.dbpedia.extraction.dump.download.Download$.main(Download.scala:16)
        at org.dbpedia.extraction.dump.download.Download.main(Download.scala)
        ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.220 s
[INFO] Finished at: 2019-01-16T09:47:28+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:run (default-cli) on project dump: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: -10000 (Exit value: -10000) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Floghi** [comment]
Hello,
The answer is in your question;
"Caused by: java.lang.IllegalArgumentException: Properties file is lacking this property: base-url"

samples of basic download properties file are included in the project;
https://github.com/dbpedia/extraction-framework/blob/master/dump/download.10000.properties
https://github.com/dbpedia/extraction-framework/blob/master/dump/download.minimal.properties

and the new QuickStart file can for sure help you;
https://github.com/dbpedia/extraction-framework/blob/master/QuickStart.md

**Comment by HadeCamacho** [comment]
Thank you. pretty much ok now. I am not good at proofreading so I'll leave it to you for now. You may now close this
