### ISSUE TITLE
Cannot pass the MiniDumpTests

### ISSUE THREAD

**Issue by regensa18** [dbpedia/extraction-framework#618]
Hi everyone,
I'm trying to run the command ../clean-install-run and I'm stuck because of the MiniDumpTests is not passing. This is the message that I got at the end of the build:

...
2020-22-04 09:10:50 | INFO | writeFile | written (append: false) target/testreports/testreport_0.html
2020-22-04 09:10:50 | INFO | writeFile | written (append: false) target/testreports/testreport_1.html
2020-22-04 09:10:50 | INFO | writeFile | written (append: false) target/testreports/testreport_2.html
- IRI Coverage Tests
20/04/22 21:10:51 ERROR riot: [line: 1, col: 12] Bad character in IRI (space): <mediawiki[space]...>
Cleaning Extraction
- RDFUnit SHACL *** FAILED ***
  org.aksw.rdfunit.io.reader.RdfReaderException: org.aksw.rdfunit.io.reader.RdfReaderException: [line: 1, col: 12] Bad character in IRI (space): <mediawiki[space]...>
  at org.aksw.rdfunit.io.reader.RdfReader.read(RdfReader.java:29)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3$$anonfun$apply$3.apply(MinidumpTests.scala:221)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3$$anonfun$apply$3.apply(MinidumpTests.scala:220)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3.apply(MinidumpTests.scala:220)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3.apply(MinidumpTests.scala:195)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  ...
  Cause: org.aksw.rdfunit.io.reader.RdfReaderException: [line: 1, col: 12] Bad character in IRI (space): <mediawiki[space]...>
  at org.aksw.rdfunit.io.reader.RdfStreamReader.read(RdfStreamReader.java:50)
  at org.aksw.rdfunit.io.reader.RdfReader.read(RdfReader.java:26)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3$$anonfun$apply$3.apply(MinidumpTests.scala:221)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3$$anonfun$apply$3.apply(MinidumpTests.scala:220)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3.apply(MinidumpTests.scala:220)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3.apply(MinidumpTests.scala:195)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  ...
  Cause: org.apache.jena.riot.RiotException: [line: 1, col: 12] Bad character in IRI (space): <mediawiki[space]...>
  at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:147)
  at org.apache.jena.riot.lang.LangEngine.raiseException(LangEngine.java:148)
  at org.apache.jena.riot.lang.LangEngine.<init>(LangEngine.java:49)
  at org.apache.jena.riot.lang.LangBase.<init>(LangBase.java:32)
  at org.apache.jena.riot.lang.LangTurtleBase.<init>(LangTurtleBase.java:71)
  at org.apache.jena.riot.lang.LangTurtle.<init>(LangTurtle.java:35)
  at org.apache.jena.riot.lang.RiotParsers.createParserTurtle(RiotParsers.java:102)
  at org.apache.jena.riot.lang.RiotParsers.createParser(RiotParsers.java:59)
  at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:190)
  at org.apache.jena.riot.RDFParser.read(RDFParser.java:352)
  ...
20/04/22 21:10:51 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
1
0
0
0
0
0
0
0
0
0
2019-05-21
12Datatype[http://www.w3.org/1999/02/22-rdf-syntax-ns#langString]
TestSuiteTests:
- ValidationExecutor
- Array
- Dataype Pattern
- Map Test
- Ntriple Test
- RDF Evaluation Report
Run completed in 1 minute, 16 seconds.
Total number of tests run: 8
Suites: completed 3, aborted 0
Tests: succeeded 7, failed 1, canceled 0, ignored 0, pending 0
*** 1 TEST FAILED ***
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Parent POM of the DBpedia framework 4.2-SNAPSHOT:
[INFO] 
[INFO] Parent POM of the DBpedia framework ................ SUCCESS [  0.768 s]
[INFO] DBpedia Core Libraries ............................. SUCCESS [01:12 min]
[INFO] DBpedia Server ..................................... SUCCESS [ 19.060 s]
[INFO] DBpedia Dump Extraction ............................ FAILURE [01:32 min]
[INFO] DBpedia Scripts .................................... SKIPPED
[INFO] Live extraction .................................... SKIPPED
[INFO] Wiktionary Dump .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:05 min
[INFO] Finished at: 2020-04-22T21:10:52+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project dump: There are test failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dump

I'm confused about why I got the error "Bad character in IRI" as I haven't touched anything in the MiniDumpTests.scala. Any help would be appreciated. Thanks!

**Comment by kurzum** [comment]
@regensa18 , 
no need to worry about it, we are working on the tests these weeks and it is just a hickup. 
You can take the previous commit or wait until @vehnem fixes it.

**Comment by kurzum** [comment]
Hm, I can't reproduce the error.
Also it seems that the tests run fine on the CI: https://travis-ci.org/github/dbpedia/extraction-framework/builds

**Comment by regensa18** [comment]
Hi @kurzum,
It seems like I haven't pulled the latest version of the extraction-framework. But after I pulled the latest version from master and run the command ../clean-run-install again, I got a different kind of error:

...
Info; cs; Minidump Tests at 00:04.718s for 42 datasets; Extraction finished for language: Czech (cs) , extracted 0 pages for 42 datasets after 00:04.718s minutes.
- IRI Coverage Tests *** FAILED ***
  org.apache.jena.atlas.web.HttpException: java.net.UnknownHostException: xmlns.com: Name or service not known
  at org.apache.jena.riot.web.HttpOp.exec(HttpOp.java:1095)
  at org.apache.jena.riot.web.HttpOp.execHttpGet(HttpOp.java:308)
  at org.apache.jena.riot.web.HttpOp.execHttpGet(HttpOp.java:367)
  at org.apache.jena.riot.RDFParser.openTypedInputStream(RDFParser.java:389)
  at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:301)
  at org.apache.jena.riot.RDFParser.parse(RDFParser.java:295)
  at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:500)
  at org.apache.jena.riot.RDFDataMgr.parseFromURI(RDFDataMgr.java:890)
  at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:221)
  at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:102)
  ...
  Cause: java.net.UnknownHostException: xmlns.com: Name or service not known
  at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
  at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
  at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
  at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
  at java.net.InetAddress.getAllByName(InetAddress.java:1193)
  at java.net.InetAddress.getAllByName(InetAddress.java:1127)
  at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
  at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:101)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
  at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
  ...
RDFUnit loaded: ./target/minidumptest/base/itwiki/20200422/itwiki-20200422-external-links.ttl.bz2
RDFUnit loaded: ./target/minidumptest/base/itwiki/20200422/itwiki-20200422-out-degree.ttl.bz2
RDFUnit loaded: ./target/minidumptest/base/itwiki/20200422/itwiki-20200422-wikipedia-links.ttl.bz2
RDFUnit loaded: ./target/minidumptest/base/itwiki/20200422/itwiki-20200422-labels.ttl.bz2
RDFUnit loaded: ./target/minidumptest/base/itwiki/20200422/itwiki-20200422-page-length.ttl.bz2
RDFUnit loaded: ./target/minidumptest/base/itwiki/20200422/itwiki-20200422-article-templates.ttl.bz2
...
RDFUnit loaded: ./target/minidumptest/base/dewiki/20200422/dewiki-20200422-pnd.ttl.bz2
RDFUnit loaded: ./target/minidumptest/base/dewiki/20200422/dewiki-20200422-short-abstracts.ttl.bz2
- RDFUnit SHACL
Cleaning Extraction
TestSuiteTests:
20/04/22 22:34:37 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
- ValidationExecutor
1
0
0
0
0
0
0
0
0
0
- Array
2019-05-21
- Dataype Pattern
12- Map Test
Datatype[http://www.w3.org/1999/02/22-rdf-syntax-ns#langString]
- Ntriple Test
Run completed in 1 minute, 45 seconds.
Total number of tests run: 7
Suites: completed 3, aborted 0
Tests: succeeded 6, failed 1, canceled 0, ignored 0, pending 0
*** 1 TEST FAILED ***
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Parent POM of the DBpedia framework 4.2-SNAPSHOT:
[INFO] 
[INFO] Parent POM of the DBpedia framework ................ SUCCESS [  0.796 s]
[INFO] DBpedia Core Libraries ............................. SUCCESS [01:12 min]
[INFO] DBpedia Server ..................................... SUCCESS [ 18.741 s]
[INFO] DBpedia Dump Extraction ............................ FAILURE [04:59 min]
[INFO] DBpedia Scripts .................................... SKIPPED
[INFO] Live extraction .................................... SKIPPED
[INFO] Wiktionary Dump .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:32 min
[INFO] Finished at: 2020-04-22T22:34:37+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project dump: There are test failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dump

The "Bad character in IRI" error is gone, but instead, I got the UnknownHostException error from xmlns.com. Do you know why that this kind of error happened? Thanks!

**Comment by kurzum** [comment]
@regensa18,
* for the first one it seems that you have used a commit with a glitch, this was fixed already. 
* for the second one it seems to be a DNS problem on your side. The tests are HTTP retrieve thes URIs:
```
 v:oneOfVocab <http://xmlns.com/foaf/0.1/> .
   v:oneOfVocab <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
   v:oneOfVocab <http://www.w3.org/2000/01/rdf-schema#> .
   v:oneOfVocab <http://www.w3.org/2003/01/geo/wgs84_pos#> . 
   v:oneOfVocab <http://www.georss.org/georss/geo_2007.owl> .
```
but they seem not reachable from the machine you are trying to install. We will remove online dependencies soon, but it will take a while. Can you just try again?

**Comment by regensa18** [comment]
Hi @kurzum,
Sorry for replying so late. I have run the command again and it worked fine now. Thanks!

**Comment by kurzum** [comment]
@regensa18  thanks for getting back
