### ISSUE TITLE
MalformedUrlException Error when doing Abstract Extraction 

### ISSUE THREAD

**Issue by regensa18** [dbpedia/extraction-framework#627]
Hi everyone,
I'm trying to do abstract extraction following the instruction [here](https://github.com/dbpedia/extraction-framework/wiki/Dbpedia-Abstract-Extraction-step-by-step-guide). I already put the wikipedia dump into my local database successfully and have already installed mediawiki. the API works fine when I called one of the pages like this: http://localhost/mediawiki/api.php?uselang=id&format=xml&action=parse&prop=text&page=Bangladesh. I already knew that AbstractExtractor is deprecated, and I'm using the NifExtractor instead. But when I am running extraction.default.properties (with adding .NifExtractor in the extractors param), I got an error like this:
```
Exception; id; Main Extraction at 00:04.094s for 70 datasets; Main Extraction failed for instance http://id.dbpedia.org/resource/Pergeseran_benua: no protocol: 
java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:611)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at org.dbpedia.extraction.util.MediaWikiConnector.retrievePage(MediaWikiConnector.scala:57)
	at org.dbpedia.extraction.mappings.NifExtractor.extract(NifExtractor.scala:60)
	at org.dbpedia.extraction.mappings.NifExtractor.extract(NifExtractor.scala:28)
	at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14)
	at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.dbpedia.extraction.mappings.CompositeExtractor.extract(CompositeExtractor.scala:14)
	at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14)
	at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.dbpedia.extraction.mappings.CompositeExtractor.extract(CompositeExtractor.scala:14)
	at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14)
	at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.dbpedia.extraction.mappings.CompositeExtractor.extract(CompositeExtractor.scala:14)
	at org.dbpedia.extraction.mappings.CompositeParseExtractor.extract(CompositeParseExtractor.scala:52)
	at org.dbpedia.extraction.mappings.CompositeParseExtractor.extract(CompositeParseExtractor.scala:12)
	at org.dbpedia.extraction.dump.extract.ExtractionJob$$anonfun$1.apply(ExtractionJob.scala:42)
	at org.dbpedia.extraction.dump.extract.ExtractionJob$$anonfun$1.apply(ExtractionJob.scala:39)
	at org.dbpedia.extraction.util.SimpleWorkers$$anonfun$apply$1$$anon$2.process(Workers.scala:43)
	at org.dbpedia.extraction.util.Workers$$anonfun$1$$anon$1.run(Workers.scala:234)
Exception; id; Main Extraction at 00:04.101s for 70 datasets; Main Extraction failed for instance http://id.dbpedia.org/resource/Resep_masakan: no protocol: 
```
I don't understand why I got the malformed URL exception when I already changed universal.properties and mwc-apiUrl param in extraction.nif.abstracts.properties according to my local mediawiki instance URL. I'm a newbie and I hope someone could help me with this because I don't know what else to do. Thank you!

**Comment by kurzum** [comment]
Hi @regensa18, 
this is deprecated. We are running the abstract extraction against the mediawiki API directly. Please use this: https://git.informatik.uni-leipzig.de/dbpedia-assoc/marvin-config

Marvin contains the configs that we are running each month (abstracts every three months). You can take the from here: https://databus.dbpedia.org/dbpedia/text/  from February or wait some weeks.

**Comment by regensa18** [comment]
Hi @kurzum,
So if I understand it correctly, is that I cannot do abstract extraction using the extraction framework myself but I can do the other extraction, right? And also can I do the abstract extraction only for my own language using the marvin-config?

**Comment by kurzum** [comment]
no, that is not what I meant. Running the extraction is possible and much easier now.
This will run the text extraction on your machine as we run it every three months:
```
# check out this repo with all config files
git clone https://git.informatik.uni-leipzig.de/dbpedia-assoc/marvin-config
cd marvin-config
# (optional) delete previous versions of the DIEF
# (~10 minutes) install dief in marvin-extraction/extraction-framework
# if you installed it already you can run `git pull && mvn clean install` to update
rm -rf marvin-extraction/extraction-framework
./setup-or-reset-dief.sh
./marvin_extraction_run.sh text
```

So you can mirror the DBpedia setup.

**Comment by regensa18** [comment]
Hi @kurzum, sorry for the late reply.
I think I will try to get the abstract by getting it from here [https://databus.dbpedia.org/dbpedia/text/](url) first. Is the abstract always updated on the first day of the month every three months?
