### ISSUE TITLE
Got FileNotFoundException when doing mvn clean install

### ISSUE THREAD

**Issue by regensa18** [dbpedia/extraction-framework#641]
Hi everyone,

I forked the extraction-framework master branch and tried to run ```mvn clean install``` and It didn't pass the DBpedia Dump Extraction part. This is the error that I got:
```
...
20/07/23 17:03:03 WARN NodeValue: Datatype format exception: "ParseResult(1788-02-22,None,None)"^^xsd:date
20/07/23 17:03:03 WARN NodeValue: Datatype format exception: "ParseResult(1860-09-21,None,None)"^^xsd:date
20/07/23 17:03:03 WARN NodeValue: Datatype format exception: "ParseResult(1860-09-21,None,None)"^^xsd:date
- Minidumps with RDFUnit/Ontology *** FAILED ***
  java.io.FileNotFoundException: ./target/testreports/onto-tests.html (No such file or directory)
  at java.io.FileOutputStream.open0(Native Method)
  at java.io.FileOutputStream.open(FileOutputStream.java:270)
  at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
  at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
  at org.dbpedia.extraction.dump.MinidumpTests.org$dbpedia$extraction$dump$MinidumpTests$$validateMinidumpWithTestSuite(MinidumpTests.scala:298)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3.apply$mcV$sp(MinidumpTests.scala:231)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3.apply(MinidumpTests.scala:226)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3.apply(MinidumpTests.scala:226)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  ...
Cleaning Extraction
TestSuiteTests:
20/07/23 17:03:04 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
1
0
0
0
0
0
0
0
0
0
2019-05-21
- ValidationExecutor
- Array
12- Dataype Pattern
- Map Test
Datatype[http://www.w3.org/1999/02/22-rdf-syntax-ns#langString]
- Ntriple Test
Run completed in 6 minutes, 22 seconds.
Total number of tests run: 8
Suites: completed 3, aborted 0
Tests: succeeded 5, failed 3, canceled 0, ignored 0, pending 0
*** 3 TESTS FAILED ***
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Parent POM of the DBpedia framework 4.2-SNAPSHOT:
[INFO] 
[INFO] Parent POM of the DBpedia framework ................ SUCCESS [  0.878 s]
[INFO] DBpedia Core Libraries ............................. SUCCESS [01:14 min]
[INFO] DBpedia Server ..................................... SUCCESS [ 19.387 s]
[INFO] DBpedia Dump Extraction ............................ FAILURE [06:39 min]
[INFO] DBpedia Scripts .................................... SKIPPED
[INFO] Live extraction .................................... SKIPPED
[INFO] Wiktionary Dump .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
...
```
Does someone know why do I get that error? I tried to run the extraction framework for my university project. Any kind of help will be appreciated. Thank you!

**Comment by StuartCHAN** [comment]
I ran the command `# extraction_framework>mvn clean install`, everything went smoothly on my machine. Then I opened the script `extraction_framework>clean-install-run` and saw that this command was suggested to be run in `#extraction_framework/core>` or `#extraction_framework/dump>`. I noticed this line in your logs `java.io.FileNotFoundException: ./target/testreports/onto-tests.html (No such file or directory)`, which's probably due to the relative paths.

**Comment by kurzum** [comment]
@regensa18 we can not reproduce your error. 
Normally, you have to run `mvn clean install` from the root directory as described here:
https://github.com/dbpedia/extraction-framework/blob/master/documentation/quickstart.md

I marked the issue as `cannot reproduce`. It will be closed in a few weeks, if you don't add more information.
