### ISSUE TITLE
georss.org causes the errors in minidump tests

### ISSUE THREAD

**Issue by jlareck** [dbpedia/extraction-framework#643]
The problem is that www.georss.org is not responding and minidump tests return next errors: 
```
IRI Coverage Tests *** FAILED ***
  org.apache.jena.atlas.web.HttpException: java.net.UnknownHostException: www.georss.org: nodename nor servname provided, or not known
  at org.apache.jena.riot.web.HttpOp.exec(HttpOp.java:1095)
  at org.apache.jena.riot.web.HttpOp.execHttpGet(HttpOp.java:308)
  at org.apache.jena.riot.web.HttpOp.execHttpGet(HttpOp.java:367)
  at org.apache.jena.riot.RDFParser.openTypedInputStream(RDFParser.java:389)
  at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:301)
  at org.apache.jena.riot.RDFParser.parse(RDFParser.java:295)
  at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:500)
  at org.apache.jena.riot.RDFDataMgr.parseFromURI(RDFDataMgr.java:890)
  at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:221)
  at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:102)

Minidumps with RDFUnit/SHACL *** FAILED ***
  java.io.FileNotFoundException: ./target/testreports/shacl-tests.html (No such file or directory)
  at java.io.FileOutputStream.open0(Native Method)
  at java.io.FileOutputStream.open(FileOutputStream.java:270)
  at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
  at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
  at org.dbpedia.extraction.dump.MinidumpTests.org$dbpedia$extraction$dump$MinidumpTests$$validateMinidumpWithTestSuite(MinidumpTests.scala:300)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$4.apply(MinidumpTests.scala:222)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$4.apply(MinidumpTests.scala:217)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)

 Minidumps with RDFUnit/Ontology *** FAILED ***
  java.io.FileNotFoundException: ./target/testreports/onto-tests.html (No such file or directory)
  at java.io.FileOutputStream.open0(Native Method)
  at java.io.FileOutputStream.open(FileOutputStream.java:270)
  at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
  at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
  at org.dbpedia.extraction.dump.MinidumpTests.org$dbpedia$extraction$dump$MinidumpTests$$validateMinidumpWithTestSuite(MinidumpTests.scala:300)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3.apply$mcV$sp(MinidumpTests.scala:233)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3.apply(MinidumpTests.scala:228)
  at org.dbpedia.extraction.dump.MinidumpTests$$anonfun$3.apply(MinidumpTests.scala:228)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  ...
```
www.georss.org is not responding at least 2 weeks and I think that maybe it is better to remove some tests from `dbpedia-specific-ci-tests.ttl` that are related to www.georss.org:
```
<#georss>
   a v:TestGenerator ;
   v:trigger trigger:georss ;
   v:validator validator:georss .


validator:georss
   a v:IRI_Validator ;
   v:oneOfVocab <http://www.georss.org/georss/geo_2007.owl> .

trigger:georss
   a v:RDF_IRI_Trigger ;
   trigger:pattern "^http://www.georss.org/georss/.*" ;
   rdfs:label "georss trigger" ;
   rdfs:comment "http://www.georss.org/georss/" .

```

**Comment by JJ-Author** [comment]
I suggest that you try a hotfix and use https://web.archive.org/web/20200115012943/http://www.georss.org/georss/geo_2007.owl as replacement. Long-term go would be to use archivo.dbpedia.org as failover.

**Comment by kurzum** [comment]
@JJ-Author @yum-yab  assigning this to you. This should use archivo. Please make it work.

**Comment by JJ-Author** [comment]
@kurzum should be fixed for now

https://github.com/dbpedia/extraction-framework/commit/91acdc4c981d4438066eec2eedded5f83cf30f50
