### ISSUE TITLE
dief.tools redirects

### ISSUE THREAD

**Issue by kurzum** [dbpedia/extraction-framework#696]
http://dief.tools.dbpedia.org/server/extraction/en/extract?title=Frances+Mcdormand&revid=&format=turtle-triples&extractors=custom

Mcdormand (not McDormand) is a redirect page: https://en.wikipedia.org/w/index.php?title=Frances_Mcdormand&action=edit

the extractor does not create a proper redirect link, maybe the redirectExtractor is not active in the config.

**Comment by JJ-Author** [comment]
I get the following when trying to activate. I reuse this issue to track the bug. 

Exception: | java.lang.NullPointerException
-- | --
Stacktrace: | java.lang.NullPointerException at org.dbpedia.extraction.mappings.RedirectExtractor.extract(RedirectExtractor.scala:33) at org.dbpedia.extraction.mappings.RedirectExtractor.extract(RedirectExtractor.scala:13) at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14) at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252) at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104) at org.dbpedia.extraction.mappings.CompositeExtractor.extract(CompositeExtractor.scala:14) at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14) at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35) at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252) at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104) at org.dbpedia.extraction.mappings.CompositeExtractor.extract(CompositeExtractor.scala:14) at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14) at org.dbpedia.extraction.mappings.CompositeExtractor$$anonfun$extract$1.apply(CompositeExtractor.scala:14) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252) at scala.collection.immutable.List.foreach(List.scala:381) at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252) at scala.collection.immutable.List.flatMap(List.scala:344) at org.dbpedia.extraction.mappings.CompositeExtractor.extract(CompositeExtractor.scala:14) at org.dbpedia.extraction.mappings.CompositeParseExtractor.extract(CompositeParseExtractor.scala:52) at org.dbpedia.extraction.mappings.CompositeParseExtractor.extract(CompositeParseExtractor.scala:12) at org.dbpedia.extraction.server.ExtractionManager$$anonfun$extract$1.apply(ExtractionManager.scala:72) at org.dbpedia.extraction.server.ExtractionManager$$anonfun$extract$1.apply(ExtractionManager.scala:71) at org.dbpedia.extraction.util.WikiApi$$anonfun$processPages$1$$anonfun$apply$1.apply(WikiApi.scala:157) at org.dbpedia.extraction.util.WikiApi$$anonfun$processPages$1$$anonfun$apply$1.apply(WikiApi.scala:149) at scala.collection.Iterator$class.foreach(Iterator.scala:743) at scala.collection.AbstractIterator.foreach(Iterator.scala:1195) at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) at scala.collection.AbstractIterable.foreach(Iterable.scala:54) at org.dbpedia.extraction.util.WikiApi$$anonfun$processPages$1.apply(WikiApi.scala:149) at org.dbpedia.extraction.util.WikiApi$$anonfun$processPages$1.apply(WikiApi.scala:148) at scala.collection.Iterator$class.foreach(Iterator.scala:743) at scala.collection.AbstractIterator.foreach(Iterator.scala:1195) at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) at scala.collection.AbstractIterable.foreach(Iterable.scala:54) at org.dbpedia.extraction.util.WikiApi.processPages(WikiApi.scala:148) at org.dbpedia.extraction.util.WikiApi$$anon$2$$anonfun$foreach$2.apply(WikiApi.scala:141) at org.dbpedia.extraction.util.WikiApi$$anon$2$$anonfun$foreach$2.apply(WikiApi.scala:138) at scala.collection.Iterator$class.foreach(Iterator.scala:743) at scala.collection.AbstractIterator.foreach(Iterator.scala:1195) at org.dbpedia.extraction.util.WikiApi$$anon$2.foreach(WikiApi.scala:138) at org.dbpedia.extraction.sources.WikiSource$$anon$2.foreach(WikiSource.scala:76) at org.dbpedia.extraction.server.ExtractionManager.extract(ExtractionManager.scala:71) at org.dbpedia.extraction.server.resources.Extraction.extract(Extraction.scala:145) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288) at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1483) at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1414) at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1363) at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1353) at com.sun.jersey.server.impl.container.httpserver.HttpHandlerContainer.handle(HttpHandlerContainer.java:191) at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79) at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83) at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82) at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675) at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79) at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by JJ-Author** [comment]
@kurzum question is now whether I should disable it again.

**Comment by kurzum** [comment]
Can't you decide? What about urdu. 
LG, 
Sebastian 

⁣BlueMail for Android herunterladen ​

Am 29. Apr. 2021, 16:59, um 16:59, JJ-Author ***@***.***> schrieb:
***@***.*** question is now whether I should disable it again.

**Comment by JJ-Author** [comment]
OK decision has been made: It is a debugging tool therefore it is good to show what is broken so that people can fix it and can see that their fix made it live after a period of time ->  I am leaving it activated.

**Comment by JJ-Author** [comment]
with regard to ur language I created https://github.com/dbpedia/extraction-framework/issues/697
